/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const popularCities = [
  { name: 'الرياض', nameEn: 'Riyadh', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 24.7136, lon: 46.6753 },
  { name: 'مكة المكرمة', nameEn: 'Makkah', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 21.3891, lon: 39.8579 },
  { name: 'المدينة المنورة', nameEn: 'Madinah', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 24.4672, lon: 39.6068 },
  { name: 'جدة', nameEn: 'Jeddah', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 21.5433, lon: 39.1728 },
  { name: 'الدمام', nameEn: 'Dammam', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 26.4207, lon: 50.0888 },
  { name: 'الخبر', nameEn: 'Khobar', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 26.2765, lon: 50.2086 },
  { name: 'القصيم', nameEn: 'Al-Qassim', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 26.3260, lon: 43.9750 },
  { name: 'بريدة', nameEn: 'Buraidah', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 26.3260, lon: 43.9750 },
  { name: 'عنيزة', nameEn: 'Unaizah', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 26.0855, lon: 43.9922 },
  { name: 'تبوك', nameEn: 'Tabuk', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 28.3835, lon: 36.5662 },
  { name: 'أبها', nameEn: 'Abha', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 18.2164, lon: 42.5053 },
  { name: 'خميس مشيط', nameEn: 'Khamis Mushait', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 18.3064, lon: 42.7292 },
  { name: 'حائل', nameEn: 'Hail', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 27.5219, lon: 41.6907 },
  { name: 'نجران', nameEn: 'Najran', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 17.4933, lon: 44.1277 },
  { name: 'جازان', nameEn: 'Jazan', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 16.8892, lon: 42.5511 },
  { name: 'الباحة', nameEn: 'Al-Baha', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 20.0129, lon: 41.4677 },
  { name: 'سكاكا', nameEn: 'Sakaka', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 29.9697, lon: 40.2064 },
  { name: 'عرعر', nameEn: 'Arar', country: 'السعودية', countryEn: 'Saudi Arabia', countryCode: 'SA', lat: 30.9753, lon: 41.0381 },
  { name: 'دبي', nameEn: 'Dubai', country: 'الإمارات', countryEn: 'United Arab Emirates', countryCode: 'AE', lat: 25.2048, lon: 55.2708 },
  { name: 'أبوظبي', nameEn: 'Abu Dhabi', country: 'الإمارات', countryEn: 'United Arab Emirates', countryCode: 'AE', lat: 24.4539, lon: 54.3773 },
  { name: 'الشارقة', nameEn: 'Sharjah', country: 'الإمارات', countryEn: 'United Arab Emirates', countryCode: 'AE', lat: 25.3463, lon: 55.4209 },
  { name: 'القاهرة', nameEn: 'Cairo', country: 'مصر', countryEn: 'Egypt', countryCode: 'EG', lat: 30.0444, lon: 31.2357 },
  { name: 'الإسكندرية', nameEn: 'Alexandria', country: 'مصر', countryEn: 'Egypt', countryCode: 'EG', lat: 31.2001, lon: 29.9187 },
  { name: 'الكويت', nameEn: 'Kuwait City', country: 'الكويت', countryEn: 'Kuwait', countryCode: 'KW', lat: 29.3759, lon: 47.9774 },
  { name: 'الدوحة', nameEn: 'Doha', country: 'قطر', countryEn: 'Qatar', countryCode: 'QA', lat: 25.2854, lon: 51.5310 },
  { name: 'مسقط', nameEn: 'Muscat', country: 'عمان', countryEn: 'Oman', countryCode: 'OM', lat: 23.5859, lon: 58.4059 },
  { name: 'المنامة', nameEn: 'Manama', country: 'البحرين', countryEn: 'Bahrain', countryCode: 'BH', lat: 26.2285, lon: 50.5860 },
  { name: 'عمان', nameEn: 'Amman', country: 'الأردن', countryEn: 'Jordan', countryCode: 'JO', lat: 31.9454, lon: 35.9284 },
  { name: 'بيروت', nameEn: 'Beirut', country: 'لبنان', countryEn: 'Lebanon', countryCode: 'LB', lat: 33.8938, lon: 35.5018 },
  { name: 'بغداد', nameEn: 'Baghdad', country: 'العراق', countryEn: 'Iraq', countryCode: 'IQ', lat: 33.3152, lon: 44.3661 },
  { name: 'دمشق', nameEn: 'Damascus', country: 'سوريا', countryEn: 'Syria', countryCode: 'SY', lat: 33.5138, lon: 36.2765 },
  { name: 'القدس', nameEn: 'Jerusalem', country: 'فلسطين', countryEn: 'Palestine', countryCode: 'PS', lat: 31.7683, lon: 35.2137 },
  { name: 'تونس', nameEn: 'Tunis', country: 'تونس', countryEn: 'Tunisia', countryCode: 'TN', lat: 36.8065, lon: 10.1815 },
  { name: 'الجزائر', nameEn: 'Algiers', country: 'الجزائر', countryEn: 'Algeria', countryCode: 'DZ', lat: 36.7525, lon: 3.0420 },
  { name: 'الرباط', nameEn: 'Rabat', country: 'المغرب', countryEn: 'Morocco', countryCode: 'MA', lat: 34.0209, lon: -6.8416 },
  { name: 'الدار البيضاء', nameEn: 'Casablanca', country: 'المغرب', countryEn: 'Morocco', countryCode: 'MA', lat: 33.5731, lon: -7.5898 },
  { name: 'لندن', nameEn: 'London', country: 'المملكة المتحدة', countryEn: 'United Kingdom', countryCode: 'GB', lat: 51.5074, lon: -0.1278 },
  { name: 'باريس', nameEn: 'Paris', country: 'فرنسا', countryEn: 'France', countryCode: 'FR', lat: 48.8566, lon: 2.3522 },
  { name: 'نيويورك', nameEn: 'New York', country: 'الولايات المتحدة', countryEn: 'USA', countryCode: 'US', lat: 40.7128, lon: -74.0060 },
  { name: 'تورونتو', nameEn: 'Toronto', country: 'كندا', countryEn: 'Canada', countryCode: 'CA', lat: 43.6532, lon: -79.3832 },
  { name: 'سيدني', nameEn: 'Sydney', country: 'أستراليا', countryEn: 'Australia', countryCode: 'AU', lat: -33.8688, lon: 151.2093 },
  { name: 'إسطنبول', nameEn: 'Istanbul', country: 'تركيا', countryEn: 'Turkey', countryCode: 'TR', lat: 41.0082, lon: 28.9784 },
  { name: 'جاكرتا', nameEn: 'Jakarta', country: 'إندونيسيا', countryEn: 'Indonesia', countryCode: 'ID', lat: -6.2088, lon: 106.8456 },
  { name: 'كوالالمبور', nameEn: 'Kuala Lumpur', country: 'ماليزيا', countryEn: 'Malaysia', countryCode: 'MY', lat: 3.1390, lon: 101.6869 },
];
