#!/usr/bin/env python3
"""Render idempotent SQL for the evidence-eligible Niswah V1 KB.

Input is generated/PRODUCTION_KB_CANDIDATES.csv, itself produced only after
all denominator/quarantine checks pass. The resulting SQL never references the
43 fail-closed Fiqh rows because they cannot appear in the candidate file.
"""

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KB = ROOT / 'production-readiness-results' / 'knowledge-base'
GENERATED = KB / 'generated'
INPUT = GENERATED / 'PRODUCTION_KB_CANDIDATES.csv'
OUTPUT = GENERATED / 'PRODUCTION_KB_SEED.sql'

EXPECTED_TOTAL = 211
EXPECTED_HEALTH = 74
EXPECTED_FIQH = 137


def q(value: str | None) -> str:
    if value is None or value == '':
        return 'null'
    return "'" + value.replace("'", "''") + "'"


def b(value: str) -> str:
    return 'true' if value.lower() == 'true' else 'false'


def read_rows():
    with INPUT.open(encoding='utf-8', newline='') as f:
        return list(csv.DictReader(f))


rows = read_rows()
if len(rows) != EXPECTED_TOTAL:
    raise SystemExit(f'Expected {EXPECTED_TOTAL} candidates, got {len(rows)}')
if sum(r['domain'] == 'FIQH' for r in rows) != EXPECTED_FIQH:
    raise SystemExit('Fiqh denominator mismatch before seed rendering')
if sum(r['domain'] != 'FIQH' for r in rows) != EXPECTED_HEALTH:
    raise SystemExit('Health/Safety denominator mismatch before seed rendering')

sql = [
    '-- AUTO-GENERATED by scripts/render_kb_seed_sql.py. DO NOT EDIT BY HAND.',
    '-- Source of truth: audited KB CSVs + build_kb_production_candidates.py.',
    'begin;',
]

for r in rows:
    source_key = r['primary_source_key']
    domain = r['domain']
    source_title = r['primary_source_title']
    source_url = r['primary_url']
    evidence_state = r['evidence_state']

    sql.append(f"""
insert into public.knowledge_sources (
  source_key, domain, title, source_type, authority_tier,
  evidence_state, url_or_reference, updated_at
) values (
  {q(source_key)}, {q(domain)}, {q(source_title)}, 'CITED_REFERENCE', 'EVIDENCE_VERIFIED',
  {q(evidence_state)}, {q(source_url)}, now()
)
on conflict (source_key) do update set
  domain = excluded.domain,
  title = excluded.title,
  evidence_state = excluded.evidence_state,
  url_or_reference = excluded.url_or_reference,
  updated_at = now();
""".strip())

    sql.append(f"""
insert into public.knowledge_items (
  knowledge_key, domain, category, topic, madhhab,
  search_text_ar, search_text_en, publication_state, updated_at
) values (
  {q(r['knowledge_key'])}, {q(domain)}, {q(r['category'])}, {q(r['topic'])}, {q(r['madhhab'])},
  {q(r['search_text_ar'])}, {q(r['search_text_en'])}, {q(r['publication_state'])}, now()
)
on conflict (knowledge_key) do update set
  domain = excluded.domain,
  category = excluded.category,
  topic = excluded.topic,
  madhhab = excluded.madhhab,
  search_text_ar = excluded.search_text_ar,
  search_text_en = excluded.search_text_en,
  publication_state = excluded.publication_state,
  updated_at = now();
""".strip())

    versions = [('en', r['canonical_en'])]
    if r['canonical_ar'].strip():
        versions.append(('ar', r['canonical_ar']))

    for language, canonical in versions:
        sql.append(f"""
insert into public.knowledge_item_versions (
  knowledge_item_id, version, language, canonical_statement,
  safety_class, evidence_state, production_eligible, effective_from
)
select id, 1, {q(language)}, {q(canonical)}, {q(r['safety_class'])},
       {q(evidence_state)}, {b(r['production_eligible'])}, now()
from public.knowledge_items where knowledge_key = {q(r['knowledge_key'])}
on conflict (knowledge_item_id, version, language) do update set
  canonical_statement = excluded.canonical_statement,
  safety_class = excluded.safety_class,
  evidence_state = excluded.evidence_state,
  production_eligible = excluded.production_eligible,
  effective_from = coalesce(public.knowledge_item_versions.effective_from, excluded.effective_from),
  effective_to = null;
""".strip())

        sql.append(f"""
insert into public.knowledge_item_sources (
  knowledge_item_version_id, source_id, locator, relation_type
)
select kiv.id, ks.id, {q(r['primary_locator'])}, 'PRIMARY'
from public.knowledge_item_versions kiv
join public.knowledge_items ki on ki.id = kiv.knowledge_item_id
join public.knowledge_sources ks on ks.source_key = {q(source_key)}
where ki.knowledge_key = {q(r['knowledge_key'])}
  and kiv.version = 1
  and kiv.language = {q(language)}
on conflict (knowledge_item_version_id, source_id, locator) do nothing;
""".strip())

# Fail closed against stale data: if a previously seeded item is no longer in
# today's audited candidate set, retire it rather than leaving it retrievable.
keys = ', '.join(q(r['knowledge_key']) for r in rows)
sql.append(f"""
update public.knowledge_items
set publication_state = 'RETIRED', updated_at = now()
where publication_state = 'PUBLISHED'
  and domain in ('HEALTH','SAFETY_ESCALATION','FIQH')
  and knowledge_key not in ({keys});
""".strip())

sql.append("""
update public.knowledge_item_versions kiv
set production_eligible = false, effective_to = now()
from public.knowledge_items ki
where ki.id = kiv.knowledge_item_id
  and ki.publication_state = 'RETIRED'
  and kiv.production_eligible = true;
""".strip())

sql.extend([
    'commit;',
    '-- Expected active V1 denominator after seed: 211 items (74 Health/Safety + 137 Fiqh).',
])

OUTPUT.write_text('\n\n'.join(sql) + '\n', encoding='utf-8')
print(f'OK: rendered {OUTPUT} from {len(rows)} production candidates')
