#!/usr/bin/env python3
"""Render idempotent SQL for the evidence-eligible Niswah V1 KB.

Input is generated/PRODUCTION_KB_CANDIDATES.csv, itself produced only after
build_kb_production_candidates.py's disposition-master-driven checks pass.
The resulting SQL never references a fail-closed row because those rows
cannot appear in the candidate file at all (see that script's reconciliation
checks against PRODUCTION_DISPOSITION_MASTER.csv).

Every seeded knowledge_item_versions row carries qualification_note (when the
disposition master's evidence audit attached one -- never flattened into an
unconditional claim) and evidence_snapshot_commit (the frozen manifest's
commit this run is sourced from). The same run registers that commit as the
active snapshot in kb_snapshot_registry, retiring whichever commit was
previously active, so retrieval can refuse to silently serve a different
dataset than the one that passed the production-disposition gate.
"""

import json
from pathlib import Path
import csv

ROOT = Path(__file__).resolve().parents[1]
KB = ROOT / 'production-readiness-results' / 'knowledge-base'
GENERATED = KB / 'generated'
INPUT = GENERATED / 'PRODUCTION_KB_CANDIDATES.csv'
OUTPUT = GENERATED / 'PRODUCTION_KB_SEED.sql'
MANIFEST_PATH = KB / 'EVIDENCE_SNAPSHOT_FREEZE_MANIFEST.json'


def q(value: str | None) -> str:
    if value is None or value == '':
        return 'null'
    return "'" + value.replace("'", "''") + "'"


def b(value: str) -> str:
    return 'true' if value.lower() == 'true' else 'false'


def read_rows():
    with INPUT.open(encoding='utf-8', newline='') as f:
        return list(csv.DictReader(f))


rows = read_rows()
if not rows:
    raise SystemExit(f'{INPUT} is empty -- run build_kb_production_candidates.py first')

required_columns = {
    'knowledge_key', 'domain', 'category', 'topic', 'madhhab',
    'search_text_ar', 'search_text_en', 'canonical_en', 'canonical_ar',
    'safety_class', 'qualification_note', 'evidence_state',
    'evidence_snapshot_commit', 'primary_source_key', 'primary_source_title',
    'primary_locator', 'primary_url', 'publication_state', 'production_eligible',
}
missing_columns = required_columns - set(rows[0].keys())
if missing_columns:
    raise SystemExit(
        f'{INPUT} is missing required column(s) {sorted(missing_columns)} -- '
        'was it produced by the current build_kb_production_candidates.py?'
    )

snapshot_commits = {r['evidence_snapshot_commit'] for r in rows}
if len(snapshot_commits) != 1:
    raise SystemExit(
        f'All candidate rows must carry the SAME evidence_snapshot_commit; found {sorted(snapshot_commits)}'
    )
snapshot_commit = snapshot_commits.pop()

if not MANIFEST_PATH.exists():
    raise SystemExit(f'{MANIFEST_PATH} does not exist -- cannot register the active snapshot')
manifest = json.loads(MANIFEST_PATH.read_text(encoding='utf-8'))
if manifest['frozen_at_commit_sha'] != snapshot_commit:
    raise SystemExit(
        f"Candidate rows are tagged with commit {snapshot_commit}, but the current "
        f"manifest is frozen at {manifest['frozen_at_commit_sha']}. Rebuild candidates "
        "against the current manifest before rendering seed SQL."
    )

import hashlib
manifest_sha256 = hashlib.sha256(MANIFEST_PATH.read_bytes()).hexdigest()
master_csv_sha256 = manifest['production_disposition_master']['sha256']
row_counts = manifest['row_counts']

sql = [
    '-- AUTO-GENERATED by scripts/render_kb_seed_sql.py. DO NOT EDIT BY HAND.',
    '-- Source of truth: PRODUCTION_DISPOSITION_MASTER.csv + build_kb_production_candidates.py.',
    f'-- Evidence snapshot commit: {snapshot_commit}',
    'begin;',
]

for r in rows:
    source_key = r['primary_source_key']
    domain = r['domain']
    source_title = r['primary_source_title']
    source_url = r['primary_url']
    evidence_state = r['evidence_state']

    sql.append(f"""
insert into public.knowledge_sources (
  source_key, domain, title, source_type, authority_tier,
  evidence_state, url_or_reference, updated_at
) values (
  {q(source_key)}, {q(domain)}, {q(source_title)}, 'CITED_REFERENCE', 'EVIDENCE_VERIFIED',
  {q(evidence_state)}, {q(source_url)}, now()
)
on conflict (source_key) do update set
  domain = excluded.domain,
  title = excluded.title,
  evidence_state = excluded.evidence_state,
  url_or_reference = excluded.url_or_reference,
  updated_at = now();
""".strip())

    sql.append(f"""
insert into public.knowledge_items (
  knowledge_key, domain, category, topic, madhhab,
  search_text_ar, search_text_en, publication_state, updated_at
) values (
  {q(r['knowledge_key'])}, {q(domain)}, {q(r['category'])}, {q(r['topic'])}, {q(r['madhhab'])},
  {q(r['search_text_ar'])}, {q(r['search_text_en'])}, {q(r['publication_state'])}, now()
)
on conflict (knowledge_key) do update set
  domain = excluded.domain,
  category = excluded.category,
  topic = excluded.topic,
  madhhab = excluded.madhhab,
  search_text_ar = excluded.search_text_ar,
  search_text_en = excluded.search_text_en,
  publication_state = excluded.publication_state,
  updated_at = now();
""".strip())

    versions = [('en', r['canonical_en'])]
    if r['canonical_ar'].strip():
        versions.append(('ar', r['canonical_ar']))

    for language, canonical in versions:
        sql.append(f"""
insert into public.knowledge_item_versions (
  knowledge_item_id, version, language, canonical_statement, qualification_note,
  safety_class, evidence_state, evidence_snapshot_commit, production_eligible, effective_from
)
select id, 1, {q(language)}, {q(canonical)}, {q(r['qualification_note'])}, {q(r['safety_class'])},
       {q(evidence_state)}, {q(r['evidence_snapshot_commit'])}, {b(r['production_eligible'])}, now()
from public.knowledge_items where knowledge_key = {q(r['knowledge_key'])}
on conflict (knowledge_item_id, version, language) do update set
  canonical_statement = excluded.canonical_statement,
  qualification_note = excluded.qualification_note,
  safety_class = excluded.safety_class,
  evidence_state = excluded.evidence_state,
  evidence_snapshot_commit = excluded.evidence_snapshot_commit,
  production_eligible = excluded.production_eligible,
  effective_from = coalesce(public.knowledge_item_versions.effective_from, excluded.effective_from),
  effective_to = null;
""".strip())

        sql.append(f"""
insert into public.knowledge_item_sources (
  knowledge_item_version_id, source_id, locator, relation_type
)
select kiv.id, ks.id, {q(r['primary_locator'])}, 'PRIMARY'
from public.knowledge_item_versions kiv
join public.knowledge_items ki on ki.id = kiv.knowledge_item_id
join public.knowledge_sources ks on ks.source_key = {q(source_key)}
where ki.knowledge_key = {q(r['knowledge_key'])}
  and kiv.version = 1
  and kiv.language = {q(language)}
on conflict (knowledge_item_version_id, source_id, locator) do nothing;
""".strip())

# Fail closed against stale data: if a previously seeded item is no longer in
# today's audited candidate set, retire it rather than leaving it retrievable.
keys = ', '.join(q(r['knowledge_key']) for r in rows)
sql.append(f"""
update public.knowledge_items
set publication_state = 'RETIRED', updated_at = now()
where publication_state = 'PUBLISHED'
  and domain in ('HEALTH','SAFETY_ESCALATION','FIQH')
  and knowledge_key not in ({keys});
""".strip())

sql.append("""
update public.knowledge_item_versions kiv
set production_eligible = false, effective_to = now()
from public.knowledge_items ki
where ki.id = kiv.knowledge_item_id
  and ki.publication_state = 'RETIRED'
  and kiv.production_eligible = true;
""".strip())

# Register this run's frozen snapshot as the active one. Exactly one row may
# hold is_current=true at a time (enforced by a partial unique index in the
# migration) -- retire the previous current row first, in the same
# transaction, so there is never a window with zero or two "current" rows.
sql.append("""
update public.kb_snapshot_registry set is_current = false where is_current;
""".strip())

sql.append(f"""
insert into public.kb_snapshot_registry (
  commit_sha, manifest_sha256, master_csv_sha256, freeze_timestamp_utc,
  total_atoms, production_eligible_count, fail_closed_count, is_current
) values (
  {q(snapshot_commit)}, {q(manifest_sha256)}, {q(master_csv_sha256)},
  {q(manifest['freeze_timestamp_utc'])}, {row_counts['total_atoms']},
  {row_counts['production_eligible']}, {row_counts['fail_closed']}, true
);
""".strip())

sql.extend([
    'commit;',
    f"-- Active evidence snapshot after seed: {snapshot_commit} "
    f"({row_counts['production_eligible']} eligible / {row_counts['fail_closed']} fail-closed "
    f"/ {row_counts['total_atoms']} total).",
])

OUTPUT.write_text('\n\n'.join(sql) + '\n', encoding='utf-8')
print(f'OK: rendered {OUTPUT} from {len(rows)} production candidates, snapshot {snapshot_commit[:12]}')
